name: Linux WPT Tests
on:
  - push
  - workflow_dispatch

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  # These options are always constant
  CONST_BENCHER_OPTIONS: --project wusyong-s-project --token ${{ secrets.BENCHER_API_TOKEN }} --testbed ubuntu-22.04

jobs:
  linux-bencher:
    name: Bencher
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 0
      # This is necessary to checkout the pull request if this run was triggered via a
      # `pull_request_target` event.
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          ref: refs/pull/${{ github.event.number }}/head
          fetch-depth: 0
      - uses: dklassic/bencher@github-checks
      # - name: Set bencher opts for PRs (label try run)
      #   if: github.event_name == 'pull_request_target'
      #   run: |
      #       echo "RUN_BENCHER_OPTIONS=--branch ${{ github.event.number }}/PR \
      #       --branch-start-point ${{ github.base_ref }} \
      #       --branch-start-point-hash ${{ github.event.pull_request.base.sha }} \
      #       --branch-reset \
      #       --github-actions ${{ secrets.GITHUB_TOKEN }}" >> "$GITHUB_ENV"
      # - name: Set bencher opts for main
      #   if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      #   run: |
      #       echo "RUN_BENCHER_OPTIONS=--branch main \
      #       --github-actions ${{ secrets.GITHUB_TOKEN }}" >> "$GITHUB_ENV"
      - name: Set bencher opts for try branch
        if: ${{ github.event_name == 'push' && github.ref_name == 'try' }}
        run: |
            echo "RUN_BENCHER_OPTIONS=--branch try \
            --hash $(git rev-parse HEAD~1) \
            --branch-start-point try \
            --branch-start-point-hash $(git rev-parse HEAD) \
            --branch-reset" >> "$GITHUB_ENV"
      # - name: File size
      #   run: ./mach test-size -r --bmf-output size.json
      # - name: Speedometer
      #   run: |
      #       python3 ./mach test-speedometer -r --bmf-output speedometer.json
      # - name: Dromaeo
      #   run: |
      #       python3 ./mach test-dromaeo -r dom --bmf-output dromaeo.json
      # we join results and send all data once to have it all in one report
      # - name: Send results
      #   run: |
      #     python3 ./mach merge-bencher-reports size.json speedometer.json dromaeo.json --bmf-output b.json
      #     bencher run --adapter json --file b.json ${{ env.CONST_BENCHER_OPTIONS }} $RUN_BENCHER_OPTIONS
      - name: Send results
        run: |
          bencher run --adapter json --file test.json ${{ env.CONST_BENCHER_OPTIONS }} $RUN_BENCHER_OPTIONS